name: Gwlevels
version: ${project.version}
main: me.lightdream.gwlevels.Gwlevels
api-version: 1.16
authors: [ _LightDream ]
depend: [PlaceholderAPI, Vault]
commands:
  calculate:
    usage: /<command>
  level:
    usage: /<command>
  dev:
    usage: /<command>
  admin:
    usage: /<command>
  gw:
    usage: /<command>