name: Gwlevels
version: ${project.version}
main: me.lightdream.gwlevels.Gwlevels
api-version: 1.16
authors: [ _LightDream ]
depend: [PlaceholderAPI, Vault]
commands:
  dev-main:
    usage: /<command>
  gwadmin:
    usage: /<command>
  gwlevel:
    usage: /<command>
  gwtop:
    usage: /<command>